@BaiKT4_WebhookService_HostAddress = http://localhost:3001

GET {{BaiKT4_WebhookService_HostAddress}}/health
Accept: application/json

###

GET {{BaiKT4_WebhookService_HostAddress}}/webhook?hub.mode=subscribe&hub.verify_token=baitk4-dev-token&hub.challenge=123456
Accept: text/plain

###

POST {{BaiKT4_WebhookService_HostAddress}}/webhook
Content-Type: application/json

{
  "object": "page",
  "entry": [
    {
      "id": "123456789",
      "time": 1777087800,
      "changes": [
        {
          "field": "feed",
          "value": {
            "item": "comment",
            "verb": "add",
            "comment_id": "987654321",
            "post_id": "123456789_111111",
            "message": "Bai viet rat hay",
            "created_time": "2026-04-25T12:30:00+07:00",
            "from": {
              "id": "10001",
              "name": "Nguyen Van A"
            }
          }
        }
      ]
    }
  ]
}

###
